name: chat_com_deus
description: "A spiritual assistant where users can ask questions and receive Bible-based answers from an AI."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  
  # Localization
  easy_localization: ^3.0.5
  
  # Backend & Auth
  supabase_flutter: ^2.5.0
  
  # Firebase (for push notifications)
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  
  # Ads
  google_mobile_ads: ^4.0.0
  
  # Payments
  flutter_stripe: ^11.0.0
  
  # Utilities
  intl: ^0.20.2
  uuid: ^4.5.1
  shared_preferences: ^2.3.2
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  
  assets:
    - assets/translations/
    - assets/images/ 